"""
STREESHIELD Phase 13A
AI Report Generator

This module creates a structured AI analysis report
from an existing deepfake detection result.

This phase does NOT modify the existing CNN,
3D CNN, preprocessing, or Streamlit application.
"""


# ==================================================
# REPORT GENERATOR
# ==================================================

class STREESHIELDReportGenerator:

    def __init__(self):

        self.project_name = "STREESHIELD"


    # ==================================================
    # GENERATE REPORT
    # ==================================================

    def generate_report(
        self,
        detection_type,
        model_name,
        prediction,
        confidence,
        ai_explanation
    ):
        """
        Generate a structured STREESHIELD AI report.

        Parameters
        ----------
        detection_type : str
            Image or Video

        model_name : str
            Basic CNN or 3D CNN

        prediction : str
            REAL or FAKE

        confidence : float
            Prediction confidence percentage

        ai_explanation : str
            Explanation generated by the AI layer

        Returns
        -------
        str
            Formatted AI report
        """

        detection_type = str(
            detection_type
        ).strip()

        model_name = str(
            model_name
        ).strip()

        prediction = str(
            prediction
        ).strip().upper()

        confidence = float(
            confidence
        )

        ai_explanation = str(
            ai_explanation
        ).strip()


        # ------------------------------------------
        # VALIDATION
        # ------------------------------------------

        if prediction not in [
            "REAL",
            "FAKE"
        ]:

            raise ValueError(
                "Prediction must be REAL or FAKE."
            )


        if confidence < 0 or confidence > 100:

            raise ValueError(
                "Confidence must be between 0 and 100."
            )


        if not ai_explanation:

            ai_explanation = (
                "No AI explanation was provided."
            )


        # ------------------------------------------
        # CREATE REPORT
        # ------------------------------------------

        report = f"""
========================================
        STREESHIELD AI REPORT
========================================

Project        : STREESHIELD

Detection Type : {detection_type}

Model          : {model_name}

Prediction     : {prediction}

Confidence     : {confidence:.2f}%


----------------------------------------
AI EXPLANATION
----------------------------------------

{ai_explanation}


----------------------------------------
IMPORTANT NOTE
----------------------------------------

The prediction is based on patterns
learned by the detection model.

Model confidence represents the strength
of the model output and is not a guarantee
of correctness.

A FAKE prediction should not be interpreted
as definitive proof of manipulation without
additional evidence.


========================================
        END OF AI REPORT
========================================
"""

        return report


# ==================================================
# 13A TEST
# ==================================================

if __name__ == "__main__":

    print(
        "\n========================================"
    )

    print(
        "       STREESHIELD PHASE 13A"
    )

    print(
        "       AI REPORT GENERATOR TEST"
    )

    print(
        "========================================"
    )


    # ------------------------------------------
    # CREATE REPORT GENERATOR
    # ------------------------------------------

    generator = (
        STREESHIELDReportGenerator()
    )


    # ------------------------------------------
    # SAMPLE DETECTION RESULT
    # ------------------------------------------

    report = generator.generate_report(

        detection_type="Image",

        model_name="Basic CNN",

        prediction="FAKE",

        confidence=87.42,

        ai_explanation=(
            "The Basic CNN produced a FAKE prediction "
            "with relatively high confidence. The model "
            "output was more strongly associated with "
            "the FAKE class based on the visual features "
            "learned during training."
        )
    )


    # ------------------------------------------
    # DISPLAY REPORT
    # ------------------------------------------

    print(
        report
    )


    print(
        "\n13A TEST COMPLETE."
    )